---
- hosts: [ben-macmini, ben-macbookpro]
  vars:
    install_homebrew_if_missing: true

  tasks:
    - name: Make sure homebrew bin is in path
      ansible.builtin.lineinfile:
        path: /etc/paths
        state: present
        line: '/opt/homebrew/bin'
      become: true
      become_user: root

    - name: 'add custom homebrew repos'
      community.general.homebrew_tap:
        name: [
          adoptopenjdk/openjdk,
          heroku/brew,
          homebrew/cask-versions
        ]

    - name: Install core packages via brew casks
      community.general.homebrew_cask:
        name: "{{ item }}"
      ignore_errors: yes
      with_items:
        - deepl
        - docker
        - dropbox
        - miniconda
        - visual-studio-code
        - vlc

    - name: "Install homebrew packages"
      community.general.homebrew:
        name: [
          'autoconf',
          'automake',
          'coreutils',
          'curl',
          'libtool',
          'libxslt',
          'libyaml',
          'joe',
          'mas',
          'openssl' ,
          'pkg-config',
          'unzip',
          'vim',
          'watchman',
          'xz',
          'yarn',
          'zlib',
        ]
        state: present
        update_homebrew: yes

    - name: "Install from Mac app store"
      shell: /opt/homebrew/bin/mas install {{ item }}
      with_items:
        - 1432731683 # Adblock Plus
        - 302584613 # Kindle   
        - 310633997 # WhatsApp
        - 6444050820 # Draw Things
        - 1035236694 # Commander One
        - 823766827 # OneDrive
        - 784801555 # Onenote
        - 462054704 # Microsoft Word 
        - 462058435 # Microsoft Excel
        - 462062816 # Microsoft PowerPoint
        - 985367838 # Microsoft Outlook  
        - 640199958 # Developer
        - 497799835 # XCode
