name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hl7v2:$(date +%s)
    - uses: addnab/docker-run-action@v3
    - name: Run Pytest
      with:
      image: localpytest:latest
      run: pytest 
